[package]
name = "image-viewer"
version = "0.3.0"
edition = "2021"
license-file = "LICENSE"
authors = ["Erwan BERNARD"]
homepage = "https://github.com/edmBernard/image-viewer-rs"
description = "Image Viewer that allow comparison side-by-side, in grid or in stack."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.19", default-features = false, features = [
	"default_app",
	"std",
	"2d_bevy_render",
	"ui_bevy_render",
	"bevy_winit",
	"default_font",
	"multi_threaded",
	"keyboard",
	"mouse",
	"touch",
	"x11",
	"wayland",
	"tonemapping_luts",
	"zstd_rust",
	"serialize",
	"jpeg",
	"bmp",
] }
bevy_egui = "0.41"
clap = { version = "4", features = ["derive"] }
image = "0.25"
home = "0.5"
serde = "1"
serde_json = "1"
toml = "1"
regex = "1"
moxcms = "0.9.0"

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSString", "NSURL", "NSArray"] }

[build-dependencies]
winresource = "0.1.30"

[package.metadata.bundle]
identifier = "io.github.edmbernard.image-viewer-rs"
resources = ["assets/"]  # Shipped assets are not currently used. But it allow to bundle license copy.
icon = ["assets/icons/128x128.png", "assets/icons/128x128@2x.png", "assets/icons/256x256.png", "assets/icons/256x256@2x.png"]
osx_info_plist_exts = ["assets/macos/info_plist_ext.xml"]
